### ISSUE TITLE
[Bug Report] - Unhandled schema type 'boolean'

### ISSUE THREAD

**Issue by andreadangel1** [nickshoe/asyncapi-php-template#3]
**Environment details**
-PHP version: 8.1.16

**Description**
If I have a schema with a boolean type property, the code won't be generated. It will instead give an error in the console log.

**Example**
I have an object-type schema like this into the asyncapi .yaml file, with the "superUser" boolean property:
```
User:
      type: object
      required:
        - id
        - firstName
        - lastName
        - email
      properties:
        id:
          type: integer
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        dateOfBirth:
          type: string
          format: date
        superUser:
          type: boolean
```
If we go to the console log after launching the code generation prompt, we will see this error:
```
Something went wrong:
Error: Unhandled schema type 'boolean'.
    at ClassHierarchyEvaluator.determineSchemaClass
```
As the error says, the boolean type is not handled in the "class-hierrachy-evaluator.js" file.
